name: Schools
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Related Dependencies
  cloud_functions: ^0.7.0+1
  cloud_firestore: ^0.14.3
  firebase_storage: ^4.0.0
  firebase_helpers: ^0.2.1
  firebase_auth:  #Added by Nayan for Sign in
  google_sign_in: #Added by Nayan for Sign in
  firebase_core: ^0.5.2
  firebase: ^7.3.2 
<<<<<<< HEAD
  firebase_database: ^4.3.0
  firebase_analytics: ^6.2.0
  firebase_messaging: ^7.0.3 #Added By Nayan for Push Notifications
  flutter_local_notifications: ^3.0.1+7
=======
  firebase_messaging: #Added By Nayan for Push Notifications
>>>>>>> dbaef9a57b239d1773c9fc6912808da7b15337f4

  # Other Dependencies
  grouped_buttons:
  image_picker: ^0.6.7
  date_utils:         #Added by Tushar for attendance
  excel:              #Added by Tushar for xlsx file handling 
  flutter_downloader: #Added by Tushar for downloading files in android
  mime_type:          #Added by Tushar for uploading files to firebase
  open_file: ^3.0.3
  overlay_support: ^1.0.5
  awesome_notifications: ^0.0.5+2
  pl_notifications: ^0.0.3+1 
  flutter_cache:
  
  image_cropper:
  flutter_speed_dial:
  table_calendar:
  font_awesome_flutter:
  random_string:
  jitsi_meet: #Added by Nayan for video chatting using jitsi
  bubble:       #Added by Nayan for Chat/Discussions
  pie_chart:    #Added by Ishita for subject Details
  socket_io_client:   #Added by Ayush for Vo/Vicalling
  provider:           #Added by Ayush for Vo/Vicalling
  universal_platform: #Added by Ishita for differentiating by different platforms
  universal_html:
  universal_io:
  shared_preferences: #Added by Nayan for storing the data locally
  flutter_staggered_animations: #Added By Ishita for Students List
  awesome_dialog: #Added By Ishita for Student List
  file_picker: ^2.0.1 #Added By Nayan for chat
  path_provider:  #Added By Nayan for downloading files
  permission_handler: #Added By Nayan for downloading files
  url_launcher: #Added By Nayan for viewing files
    #http to download PDF
  http:
    #Open PDF in a viewer
  flutter_full_pdf_viewer:
  toast:  #Added by Ishita for add students
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "notification_icon"
  ios: true
  image_path: "assets/AppIcon/notification.png"
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Iconss
      fonts:
        - asset: fonts/Iconss.ttf
    - family:  Iconsss
      fonts:
        - asset: fonts/Iconsss.ttf
    - family:  Iconssss
      fonts:
        - asset: fonts/Iconssss.ttf
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf



  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/management.png
    - assets/images/student.png
    - assets/images/addstd.png
    - assets/images/addsdt.png
    - assets/images/download.png
    - assets/images/employee2.png
    - assets/images/employee.png
    - assets/images/dev.jpg
    - assets/images/assignment.png
    - assets/images/attendance.jpg
    - assets/images/fteacher.png
    - assets/images/mteacher.png
    - assets/images/grades.png
    - assets/images/tutorials.png
    - assets/images/assignment2.png
    - assets/images/attendance2.jpg
    - assets/images/fteacher2.jpg
    - assets/images/mteacher2.jpg
    - assets/images/grades2.jpg
    - assets/images/tutorials2.jpg
    - assets/images/profile.jpg
    - assets/images/coverimage.jpg
    - assets/images/sheet.png
    - assets/images/LOGO.jpeg
    - assets/AppIcon/Logo.png
    - assets/AppIcon/Logo.svg
    - assets/AppIcon/notification.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages