/// Flutter icons Iconss
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconss
///      fonts:
///       - asset: fonts/Iconss.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Iconss {
  Iconss._();

  static const _kFontFam = 'Iconss';
  static const _kFontPkg = null;

  static const IconData user_edit = IconData(0xf4ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_graduate = IconData(0xf501, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_minus = IconData(0xf503, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_tie = IconData(0xf508, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
