/// Flutter icons Iconsss
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iconsss
///      fonts:
///       - asset: fonts/Iconsss.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Iconsss {
  Iconsss._();

  static const _kFontFam = 'Iconsss';
  static const _kFontPkg = null;

  static const IconData book = IconData(0xf02d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_cog = IconData(0xf4fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_reader = IconData(0xf5da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
